language: ruby

services:
  - docker


# To handle 'not get uid/gid'
RUN npm install -g yarn gulp        
RUN npm config set unsafe-perm true

before_install:
  - docker pull mongo:latest
  - docker run --name mongo -p 27017:27017 -d mongo mongod --smallfiles
  - docker build --tag core .
  - docker ps -a


script:
  - docker ps -a

branches:
  only:
    - master
    - production

notifications:
  slack: wrioos:XDZWFBrf9TDtoEOcw5YGBM4a

deploy:
  - provider: s3
    access_key_id:
      secure: RSbJV8MZaIxbpJA0yT/qp+7nBPzQmjkzPErb8t4ZpAkebsTVKAd7/e//fXFJguSUoPx57zGRxCJNTvuF7uZSZ4Vl85JZXInzQnKI5nFP8FfqqSZmH6mYf6+m0MFHVYy4s0SX5/IGkMCRIFoKK3PJ7HnizrYdmTOywcSxrsSI8F0=
    secret_access_key:
      secure: bxuBwOeamiW+xysEbyJ1r1KhcHg5WtJUqDv8tIpw1t06D6AeJ0frny64bPWYq9DiOYJetqifUq9ppRdafVP4JbR5rbn9ryXkvR+NeySZ0tQZask9udwsxK8bz/YC00511TTYt7l3x24neIWqQJ3HNMJSU4bXMusdlK/wGYymn/o=
    bucket: wrioos.com
    upload-dir: Core-WRIO-App
    acl: public_read
